# Generated by Django 4.0.1 on 2022-01-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='maxCapacity',
        ),
    ]
