# Generated by Django 4.0.1 on 2022-01-30 18:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_remove_vehicle_maxcapacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number'),
        ),
    ]
