# Generated by Django 4.0.1 on 2022-01-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RideShareServiceUser',
        ),
    ]
